#!/usr/bin/env python3

#This script takes gunzipped FASTQ files generated by illumina sequencing as input. 
#Sequences are then subject to quality control, de novo assembly via 3 separate tools, then the best assembly is selected via post-assembly QC. 
#This final assembly is then run through BLAST to determine species identification